#server:
#  port: 10002
#spring:
#  application:
#    name: server-gateway
#    #  main:
#    # allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 7777
#        dashboard: 127.0.0.1:8888
#      web-context-unify: false
#      eager: true #true表示立即注册到Sentinel
#
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowCredentials: true
#            allowedHeaders: "*"
#      discovery:
#        locator:
#          enabled: true
#          route-id-prefix: gateway- #生成流控规则API名称的前缀
##      routes:
##        - id: user-gateway
##          uri: lb://server-user
##          order: 1
##          predicates:
##            - Path=/server-user/**
##          filters:
##            - StripPrefix=1
##
##        - id: product-gateway
##          uri: lb://server-product
##          order: 1
##          predicates:
##            - Path=/server-product/**
##          filters:
##            - StripPrefix=1
##
##        - id: order-gateway
##          uri: lb://server-order
##          order: 1
##          predicates:
##            - Path=/server-order/**
##          filters:
##            - StripPrefix=1
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false